
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "5005:5005" # Expose the app on localhost:3003
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/nyf/service/backend
      - /nyf/service/backend/node_modules
    command: pm2-runtime dist/index.js

  redis:
    image: redis/redis-stack:latest # Use the Redis Stack image
    container_name: my-redis
    ports:
      - "6379:6379" # Expose Redis core on localhost:6379
      - "8001:8001" # Expose RedisInsight on localhost:8001
    volumes:
      - redis-data:/data

volumes:
  redis-data:

















# version: '3.9'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: my-app
#     ports:
#       - "3003:3003" # Expose the app on localhost:3003
#     depends_on:
#       - redis
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#     volumes:
#       - .:/nyf/service/backend
#       - /nyf/service/backend/node_modules
#     command: pm2-runtime dist/index.js

#   redis:
#     image: redis:6
#     container_name: my-redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis-data:/data

# volumes:
#   redis-data:
